palavra = input('Digite algo:')
print(f'O tipo dessa variável é {type(palavra)}')
print(f'possui espaço : {palavra.isspace()}')
print(f'possui número :{palavra.isnumeric()}')
print(f'possui letras:{palavra.isalpha()}')
print(f'possui letras ou números : {palavra.isalnum()}')
print(f'está em letra maiuscula : {palavra.isupper()}')
print(f'está em letra minúscula : {palavra.islower()}')
print(f'A primeira letra é maiúscula : {palavra.istitle()}')
